sudo: false
language: python
python:
  - 2.7
cache:
  pip: true
  directories:
    - eggs
before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -N -t 3 annotate
install:
  - bin/buildout -N -t 3
script:
  - bin/test
notifications:
  email:
    - steve@dcn.org
